

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: randomfacts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  quarkus-app:
    build: .
    platform: linux/arm64
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://postgres:5432/randomfacts
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
      QUARKUS_REDIS_HOSTS: redis://redis:6379 
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - quarkus-app
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]  # Enables persistence
    volumes:
      - redis_data:/data  # Persist Redis data

volumes:
  redis_data:
